package org.deals.framework.bean;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractPageState generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractPageState implements PersistentObject, java.io.Serializable {


    // Fields    

     private Integer psId;
     private String psName;
     private String psDescription;
     private Set webPages = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractPageState() {
    }

	/** minimal constructor */
    public AbstractPageState(String psName) {
        this.psName = psName;
    }
    
    /** full constructor */
    public AbstractPageState(String psName, String psDescription, Set webPages) {
        this.psName = psName;
        this.psDescription = psDescription;
        this.webPages = webPages;
    }

   
    // Property accessors

    public Integer getPsId() {
        return this.psId;
    }
    
    public void setPsId(Integer psId) {
        this.psId = psId;
    }

    public String getPsName() {
        return this.psName;
    }
    
    public void setPsName(String psName) {
        this.psName = psName;
    }

    public String getPsDescription() {
        return this.psDescription;
    }
    
    public void setPsDescription(String psDescription) {
        this.psDescription = psDescription;
    }

    public Set getWebPages() {
        return this.webPages;
    }
    
    public void setWebPages(Set webPages) {
        this.webPages = webPages;
    }
   








}