package org.deals.framework.bean;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractPageType generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractPageType implements PersistentObject, java.io.Serializable {


    // Fields    

     private Integer ptId;
     private PageType pageType;
     private String ptName;
     private String ptDescription;
     private Set pageTypes = new HashSet(0);
     private Set webPages = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractPageType() {
    }

    
    /** full constructor */
    public AbstractPageType(PageType pageType, String ptName, String ptDescription, Set pageTypes, Set webPages) {
        this.pageType = pageType;
        this.ptName = ptName;
        this.ptDescription = ptDescription;
        this.pageTypes = pageTypes;
        this.webPages = webPages;
    }

   
    // Property accessors

    public Integer getPtId() {
        return this.ptId;
    }
    
    public void setPtId(Integer ptId) {
        this.ptId = ptId;
    }

    public PageType getPageType() {
        return this.pageType;
    }
    
    public void setPageType(PageType pageType) {
        this.pageType = pageType;
    }

    public String getPtName() {
        return this.ptName;
    }
    
    public void setPtName(String ptName) {
        this.ptName = ptName;
    }

    public String getPtDescription() {
        return this.ptDescription;
    }
    
    public void setPtDescription(String ptDescription) {
        this.ptDescription = ptDescription;
    }

    public Set getPageTypes() {
        return this.pageTypes;
    }
    
    public void setPageTypes(Set pageTypes) {
        this.pageTypes = pageTypes;
    }

    public Set getWebPages() {
        return this.webPages;
    }
    
    public void setWebPages(Set webPages) {
        this.webPages = webPages;
    }
   








}