package org.deals.framework.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * AbstractWebPage generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractWebPage implements PersistentObject, java.io.Serializable {


    // Fields    

     private Integer wpId;
     private PageState pageState;
     private Users usersByWpLastModifier;
     private Template template;
     private PageType pageType;
     private Users usersByWpCreator;
     private String wpName;
     private String wpDescription;
     private String wpPageTitle;
     private String wpContentTitle;
     private String wpHeader;
     private String wpContent;
     private String wpFooter;
     private Date wpCreated;
     private Date wpLastModified;
     private Date wpPublished;
     private Integer wpWeight;
     private Date wpExpire;
     private String wpAuthor;
     private boolean wpPrint;
     private boolean wpSend;
     private Set APagePagesForAppChild = new HashSet(0);
     private Set APagePagesForAppParent = new HashSet(0);
     private Set APageComponentses = new HashSet(0);
     private Set AProfilePages = new HashSet(0); 
     private String wpMetaTitle;
     private String wpMetaDescription;
     private String wpMetaKeywords;
     private boolean wpCommentsOn; 
     private String wpTags;
     private Set commentses = new HashSet(0);


    // Constructors

    public boolean isWpCommentsOn() {
		return wpCommentsOn;
	}

	public void setWpCommentsOn(boolean wpCommentsOn) {
		this.wpCommentsOn = wpCommentsOn;
	}

	public String getWpMetaDescription() {
		return wpMetaDescription;
	}

	public void setWpMetaDescription(String wpMetaDescription) {
		this.wpMetaDescription = wpMetaDescription;
	}

	public String getWpMetaKeywords() {
		return wpMetaKeywords;
	}

	public void setWpMetaKeywords(String wpMetaKeywords) {
		this.wpMetaKeywords = wpMetaKeywords;
	}

	public String getWpMetaTitle() {
		return wpMetaTitle;
	}

	public void setWpMetaTitle(String wpMetaTitle) {
		this.wpMetaTitle = wpMetaTitle;
	}

	/** default constructor */
    public AbstractWebPage() {
    }

	/** minimal constructor */
    public AbstractWebPage(PageState pageState, Users usersByWpLastModifier, Template template, Users usersByWpCreator, String wpName, Date wpCreated, Date wpLastModified, Integer wpWeight) {
        this.pageState = pageState;
        this.usersByWpLastModifier = usersByWpLastModifier;
        this.template = template;
        this.usersByWpCreator = usersByWpCreator;
        this.wpName = wpName;
        this.wpCreated = wpCreated;
        this.wpLastModified = wpLastModified;
        this.wpWeight = wpWeight;
    }
    
    /** full constructor */
    public AbstractWebPage(PageState pageState, Users usersByWpLastModifier, Template template, PageType pageType, Users usersByWpCreator, String wpName, String wpDescription, String wpPageTitle, String wpContentTitle, String wpHeader, String wpContent, String wpFooter, Date wpCreated, Date wpLastModified, Date wpPublished, Integer wpWeight, Date wpExpire, String wpAuthor, boolean wpPrint, boolean wpSend, Set APagePagesForAppChild, Set APagePagesForAppParent, Set APageComponentses, Set AProfilePages, Set commentses) {
        this.pageState = pageState;
        this.usersByWpLastModifier = usersByWpLastModifier;
        this.template = template;
        this.pageType = pageType;
        this.usersByWpCreator = usersByWpCreator;
        this.wpName = wpName;
        this.wpDescription = wpDescription;
        this.wpPageTitle = wpPageTitle;
        this.wpContentTitle = wpContentTitle;
        this.wpHeader = wpHeader;
        this.wpContent = wpContent;
        this.wpFooter = wpFooter;
        this.wpCreated = wpCreated;
        this.wpLastModified = wpLastModified;
        this.wpPublished = wpPublished;
        this.wpWeight = wpWeight;
        this.wpExpire = wpExpire;
        this.wpAuthor = wpAuthor;
        this.wpPrint = wpPrint;
        this.wpSend = wpSend;
        this.APagePagesForAppChild = APagePagesForAppChild;
        this.APagePagesForAppParent = APagePagesForAppParent;
        this.APageComponentses = APageComponentses;
        this.AProfilePages = AProfilePages;
        this.commentses = commentses;
    }

   
    // Property accessors

    public Integer getWpId() {
        return this.wpId;
    }
    
    public void setWpId(Integer wpId) {
        this.wpId = wpId;
    }

    public PageState getPageState() {
        return this.pageState;
    }
    
    public void setPageState(PageState pageState) {
        this.pageState = pageState;
    }

    public Users getUsersByWpLastModifier() {
        return this.usersByWpLastModifier;
    }
    
    public void setUsersByWpLastModifier(Users usersByWpLastModifier) {
        this.usersByWpLastModifier = usersByWpLastModifier;
    }

    public Template getTemplate() {
        return this.template;
    }
    
    public void setTemplate(Template template) {
        this.template = template;
    }

    public PageType getPageType() {
        return this.pageType;
    }
    
    public void setPageType(PageType pageType) {
        this.pageType = pageType;
    }

    public Users getUsersByWpCreator() {
        return this.usersByWpCreator;
    }
    
    public void setUsersByWpCreator(Users usersByWpCreator) {
        this.usersByWpCreator = usersByWpCreator;
    }

    public String getWpName() {
        return this.wpName;
    }
    
    public void setWpName(String wpName) {
        this.wpName = wpName;
    }

    public String getWpDescription() {
        return this.wpDescription;
    }
    
    public void setWpDescription(String wpDescription) {
        this.wpDescription = wpDescription;
    }

    public String getWpPageTitle() {
        return this.wpPageTitle;
    }
    
    public void setWpPageTitle(String wpPageTitle) {
        this.wpPageTitle = wpPageTitle;
    }

    public String getWpContentTitle() {
        return this.wpContentTitle;
    }
    
    public void setWpContentTitle(String wpContentTitle) {
        this.wpContentTitle = wpContentTitle;
    }

    public String getWpHeader() {
        return this.wpHeader;
    }
    
    public void setWpHeader(String wpHeader) {
        this.wpHeader = wpHeader;
    }

    public String getWpContent() {
        return this.wpContent;
    }
    
    public void setWpContent(String wpContent) {
        this.wpContent = wpContent;
    }

    public String getWpFooter() {
        return this.wpFooter;
    }
    
    public void setWpFooter(String wpFooter) {
        this.wpFooter = wpFooter;
    }

    public Date getWpCreated() {
        return this.wpCreated;
    }
    
    public void setWpCreated(Date wpCreated) {
        this.wpCreated = wpCreated;
    }

    public Date getWpLastModified() {
        return this.wpLastModified;
    }
    
    public void setWpLastModified(Date wpLastModified) {
        this.wpLastModified = wpLastModified;
    }

    public Date getWpPublished() {
        return this.wpPublished;
    }
    
    public void setWpPublished(Date wpPublished) {
        this.wpPublished = wpPublished;
    }

    public Integer getWpWeight() {
        return this.wpWeight;
    }
    
    public void setWpWeight(Integer wpWeight) {
        this.wpWeight = wpWeight;
    }

    public Date getWpExpire() {
        return this.wpExpire;
    }
    
    public void setWpExpire(Date wpExpire) {
        this.wpExpire = wpExpire;
    }

    public String getWpAuthor() {
        return this.wpAuthor;
    }
    
    public void setWpAuthor(String wpAuthor) {
        this.wpAuthor = wpAuthor;
    }

    public boolean getWpPrint() {
        return this.wpPrint;
    }
    
    public void setWpPrint(boolean wpPrint) {
        this.wpPrint = wpPrint;
    }

    public boolean getWpSend() {
        return this.wpSend;
    }
    
    public void setWpSend(boolean wpSend) {
        this.wpSend = wpSend;
    }

    public Set getAPagePagesForAppChild() {
        return this.APagePagesForAppChild;
    }
    
    public void setAPagePagesForAppChild(Set APagePagesForAppChild) {
        this.APagePagesForAppChild = APagePagesForAppChild;
    }

    public Set getAPagePagesForAppParent() {
        return this.APagePagesForAppParent;
    }
    
    public void setAPagePagesForAppParent(Set APagePagesForAppParent) {
        this.APagePagesForAppParent = APagePagesForAppParent;
    }

    public Set getAPageComponentses() {
        return this.APageComponentses;
    }
    
    public void setAPageComponentses(Set APageComponentses) {
        this.APageComponentses = APageComponentses;
    }

	public Set getAProfilePages() {
		return AProfilePages;
	}

	public void setAProfilePages(Set profilePages) {
		AProfilePages = profilePages;
	}

	public String getWpTags() {
		return wpTags;
	}

	public void setWpTags(String wpTags) {
		this.wpTags = wpTags;
	}
	
	public Set getCommentses() {
		return this.commentses;
	}

	public void setCommentses(Set commentses) {
		this.commentses = commentses;
	}

}