package org.deals.framework.bean;

import java.util.Date;




/**
 * AbstractAPageComponents generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractAPageComponents implements PersistentObject, java.io.Serializable {


//	 Fields    

	private Integer apcId;

	private WebPage webPage;

	private APageComponentsType APageComponentsType;

	private WebComponent webComponent;

	private Date apcAssocDate;

	private String apcAlt;

	private String apcDescription;

	// Constructors

	/** default constructor */
	public AbstractAPageComponents() {
	}

	/** minimal constructor */
	public AbstractAPageComponents(Integer apcId, WebPage webPage, WebComponent webComponent) {
		this.apcId = apcId;
		this.webPage = webPage;
		this.webComponent = webComponent;
	}

	/** full constructor */
	public AbstractAPageComponents(Integer apcId, WebPage webPage, APageComponentsType APageComponentsType, WebComponent webComponent, Date apcAssocDate, String apcAlt, String apcDescription) {
		this.apcId = apcId;
		this.webPage = webPage;
		this.APageComponentsType = APageComponentsType;
		this.webComponent = webComponent;
		this.apcAssocDate = apcAssocDate;
		this.apcAlt = apcAlt;
		this.apcDescription = apcDescription;
	}

	// Property accessors
	public Integer getApcId() {
		return this.apcId;
	}

	public void setApcId(Integer apcId) {
		this.apcId = apcId;
	}

	public WebPage getWebPage() {
		return this.webPage;
	}

	public void setWebPage(WebPage webPage) {
		this.webPage = webPage;
	}

	public APageComponentsType getAPageComponentsType() {
		return this.APageComponentsType;
	}

	public void setAPageComponentsType(APageComponentsType APageComponentsType) {
		this.APageComponentsType = APageComponentsType;
	}

	public WebComponent getWebComponent() {
		return this.webComponent;
	}

	public void setWebComponent(WebComponent webComponent) {
		this.webComponent = webComponent;
	}

	public Date getApcAssocDate() {
		return this.apcAssocDate;
	}

	public void setApcAssocDate(Date apcAssocDate) {
		this.apcAssocDate = apcAssocDate;
	}

	public String getApcAlt() {
		return this.apcAlt;
	}

	public void setApcAlt(String apcAlt) {
		this.apcAlt = apcAlt;
	}

	public String getApcDescription() {
		return this.apcDescription;
	}

	public void setApcDescription(String apcDescription) {
		this.apcDescription = apcDescription;
	}
	
	
}