package org.deals.framework.bean;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractComponentType generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractComponentType implements PersistentObject, java.io.Serializable {


    // Fields    

     private Integer ctId;
     private String ctName;
     private String ctDescri;
     private Set webComponents = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractComponentType() {
    }

	/** minimal constructor */
    public AbstractComponentType(String ctName) {
        this.ctName = ctName;
    }
    
    /** full constructor */
    public AbstractComponentType(String ctName, String ctDescri, Set webComponents) {
        this.ctName = ctName;
        this.ctDescri = ctDescri;
        this.webComponents = webComponents;
    }

   
    // Property accessors

    public Integer getCtId() {
        return this.ctId;
    }
    
    public void setCtId(Integer ctId) {
        this.ctId = ctId;
    }

    public String getCtName() {
        return this.ctName;
    }
    
    public void setCtName(String ctName) {
        this.ctName = ctName;
    }

    public String getCtDescri() {
        return this.ctDescri;
    }
    
    public void setCtDescri(String ctDescri) {
        this.ctDescri = ctDescri;
    }

    public Set getWebComponents() {
        return this.webComponents;
    }
    
    public void setWebComponents(Set webComponents) {
        this.webComponents = webComponents;
    }
   








}