package org.deals.framework.bean;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractUsers generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractUsers implements PersistentObject, java.io.Serializable {


    // Fields    

     private Integer usId;
     private String usUsername;
     private String usPassword;
     private UserProfile profile;
     private String usFirstname;
     private String usSurname;
     private String usEmail;
     private Set webPagesForWpLastModifier = new HashSet(0);
     private Set webPagesForWpCreator = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractUsers() {
    }

	/** minimal constructor */
    public AbstractUsers(String usUsername, String usPassword, UserProfile profile) {
        this.usUsername = usUsername;
        this.usPassword = usPassword;
        this.profile = profile;
    }
    
    /** full constructor */
    public AbstractUsers(String usUsername, String usPassword, UserProfile profile, String usFirstname, String usSurname, String usEmail, Set webPagesForWpLastModifier, Set webPagesForWpCreator) {
        this.usUsername = usUsername;
        this.usPassword = usPassword;
        this.profile = profile;
        this.usFirstname = usFirstname;
        this.usSurname = usSurname;
        this.usEmail = usEmail;
        this.webPagesForWpLastModifier = webPagesForWpLastModifier;
        this.webPagesForWpCreator = webPagesForWpCreator;
    }

   
    // Property accessors

    public Integer getUsId() {
        return this.usId;
    }
    
    public void setUsId(Integer usId) {
        this.usId = usId;
    }

    public String getUsUsername() {
        return this.usUsername;
    }
    
    public void setUsUsername(String usUsername) {
        this.usUsername = usUsername;
    }

    public String getUsPassword() {
        return this.usPassword;
    }
    
    public void setUsPassword(String usPassword) {
        this.usPassword = usPassword;
    }

    
    public UserProfile getProfile() {
		return profile;
	}

	public void setProfile(UserProfile profile) {
		this.profile = profile;
	}

	public String getUsFirstname() {
        return this.usFirstname;
    }
    
    public void setUsFirstname(String usFirstname) {
        this.usFirstname = usFirstname;
    }

    public String getUsSurname() {
        return this.usSurname;
    }
    
    public void setUsSurname(String usSurname) {
        this.usSurname = usSurname;
    }

    public String getUsEmail() {
        return this.usEmail;
    }
    
    public void setUsEmail(String usEmail) {
        this.usEmail = usEmail;
    }

    public Set getWebPagesForWpLastModifier() {
        return this.webPagesForWpLastModifier;
    }
    
    public void setWebPagesForWpLastModifier(Set webPagesForWpLastModifier) {
        this.webPagesForWpLastModifier = webPagesForWpLastModifier;
    }

    public Set getWebPagesForWpCreator() {
        return this.webPagesForWpCreator;
    }
    
    public void setWebPagesForWpCreator(Set webPagesForWpCreator) {
        this.webPagesForWpCreator = webPagesForWpCreator;
    }
   








}