package org.deals.framework.bean;
// Generated by MyEclipse - Hibernate Tools



/**
 * APagePage generated by MyEclipse - Hibernate Tools
 */
public class APagePage extends AbstractAPagePage implements java.io.Serializable {
	
	private static final long serialVersionUID = -580478351371274328L;

	// Constructors

    /** default constructor */
    public APagePage() {
    }

	/** minimal constructor */
    public APagePage(WebPage webPageByAppChild, WebPage webPageByAppParent) {
        super(webPageByAppChild, webPageByAppParent);        
    }
    
    /** full constructor */
    public APagePage(WebPage webPageByAppChild, WebPage webPageByAppParent, Integer appWeight) {
        super(webPageByAppChild, webPageByAppParent, appWeight);        
    }
   
	public boolean isTop() {
	 return (getAppWeight()==1);
	}

	@Override
	public boolean equals(Object obj) {
		if (obj==null) return false;
		if (this==obj) return true;
		APagePage app = (APagePage)obj;
		
		if (getWebPageByAppChild().getWpId()==null&&app.getWebPageByAppChild().getWpId()==null)
		   return (getWebPageByAppParent().getWpId().equals(app.getWebPageByAppParent().getWpId()));
		else
		return (getWebPageByAppChild().getWpId().equals(app.getWebPageByAppChild().getWpId())&&
				(getWebPageByAppParent().getWpId().equals(app.getWebPageByAppParent().getWpId())));
	}
	
	

}
