package org.deals.framework.bean;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;

import org.deals.framework.factory.TemplateFactory;


/**
 * Template generated by MyEclipse - Hibernate Tools
 */
public class Template extends AbstractTemplate implements java.io.Serializable {
	
	private static final long serialVersionUID = -1555417586417527656L;

	public static int TEMPLATE_TEST_ID = 1;	
	public static String TEMPLATE_TEST_NAME = "scheda_area_istituzionale";	
	
    // Constructors

    /** default constructor */
    public Template() {
    }

	/** minimal constructor */
    public Template(String teName) {
        super(teName);        
    }
    
    /** full constructor */
    public Template(String teName, Set webPages) {
        super(teName, webPages);        
    }
   
    
    public static Template TEST_TEMPLATE() {
    	return TemplateFactory.createTestTemplate();
    }
    
    
}
