package org.deals.framework.bean;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import java.util.Set;

/**
 * UserProfile generated by MyEclipse Persistence Tools
 */
public class UserProfile extends AbstractUserProfile implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public UserProfile() {
	}

	/** minimal constructor */
	public UserProfile(Integer upId, String upName, Date upCreated) {
		super(upId, upName, upCreated);
	}

	/** full constructor */
	public UserProfile(Integer upId, String upName, String upDescription,
			Date upCreated, Date upExpire, Set userses, Set AProfilePageses,
			Set AProfileSectionses) {
		super(upId, upName, upDescription, upCreated, upExpire, userses,
				AProfilePageses, AProfileSectionses);
	}
	
	
	
	
//	 Serve per l'editing sul Repeater
	private int rowId;

   	public int getRowId() {
		return rowId;
	}

	public void setRowId(int rowId) {
		this.rowId = rowId;
	}	
	
	private boolean associated = false;
	
	public boolean isAssociated() {
		return associated;
	}

	public void setAssociated(boolean associated) {
		this.associated = associated;
	}
	
	
	
	
	////////////////////////////////////////////////////////////////////////////
	

	@Override
	public boolean equals(Object obj) {
		if (obj==null) return false;
		if (obj==this) return true;		
		return (((UserProfile)obj).getUpName().equals(getUpName())
				&& ((UserProfile)obj).getUpDescription().equals(getUpDescription()));
	}

	//public static UserProfile all() {
	//	return new UserProfile(777,"admin","Amministratore",new Date(),null);
	//}
	

}
