package org.deals.framework.bean;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * Users generated by MyEclipse - Hibernate Tools
 */
public class Users extends AbstractUsers implements java.io.Serializable {

	//private static final long serialVersionUID = 2958141844405575211L;

//	public static final int ALEX_ID = 1;
//	public static final int SIMONE_ID = 2;
//	public static final int DENNIS_ID = 3;	
	
    // Constructors

    /** default constructor */
    public Users() {
    }

	/** minimal constructor */
    public Users(String usUsername, String usPassword, UserProfile profile) {
        super(usUsername, usPassword, profile);        
    }
    
    /** full constructor */
    public Users(String usUsername, String usPassword, UserProfile profile, String usFirstname, String usSurname, String usEmail, Set webPagesForWpLastModifier, Set webPagesForWpCreator) {
        super(usUsername, usPassword, profile, usFirstname, usSurname, usEmail, webPagesForWpLastModifier, webPagesForWpCreator);        
    }
/*
    
    public static Users ALEX() {
    	return UsersFactory.createAlexUser();
    }
    
    public static Users SIMONE() {
    	return UsersFactory.createSimoneUser();
    }
    
    public static Users DENNIS() {
    	return UsersFactory.createDennisUser();
    }
*/    
	// Serve per l'editing sul Repeater
	private int rowId;

   	public int getRowId() {
		return rowId;
	}

	public void setRowId(int rowId) {
		this.rowId = rowId;
	}

	public String toXML() {
    		StringBuffer sb = new StringBuffer();
    		sb.append("<user id=\"" + getUsId() + "\">");
    		sb.append("<username>" + getUsUsername() + "</username>");
    		sb.append("<profile>" + getProfile().getUpName() + "</profile>");		
    		sb.append("<firstname>" + getUsFirstname() + "</firstname>");		
    		sb.append("<surname>" + getUsSurname() + "</surname>");		
    		sb.append("<email>" + getUsEmail() + "</email>");		
    		sb.append("</user>");
    		return sb.toString();
    }        
    
}



