package org.deals.framework.bean;

// Generated by MyEclipse - Hibernate Tools

import java.util.Date;
import java.util.Set;

/**
 * WebComponent generated by MyEclipse - Hibernate Tools
 */
public class WebComponent extends AbstractWebComponent implements java.io.Serializable {

	private static final long serialVersionUID = 6187190716218150887L;	
	// Constructors


	/** default constructor */
	public WebComponent() {
	}

	/** minimal constructor */
	public WebComponent(ComponentType componentType) {
		super(componentType);
	}

	/** full constructor */
	public WebComponent(ComponentType componentType, String rlTitle, String rlContent, String rlTarget, String rlHref, String wrName, String wrDescription, String wrMimetype,
			String wrAlt, Date wcInsertDate, Set APageComponentses) {
		super(componentType, rlTitle, rlContent, rlTarget, rlHref, wrName, wrDescription, wrMimetype, wrAlt, wcInsertDate, APageComponentses);
	}

	public String toXML() {
		return "";
	}

	/**
	 * viene usato dall'associazione 
	 * @return
	 */
	public String toXML2() {
		return "";
	}
	private boolean select;

	// Serve per l'editing sul Repeater
	private int rowId;

	// Serve per la cancellazione sul Repeater
	private boolean deleted;

	public boolean isSelect() {
		return select;
	}

	public void setSelect(boolean select) {
		this.select = select;
	}

	public int getRowId() {
		return rowId;
	}

	public void setRowId(int rowId) {
		this.rowId = rowId;
	}

	public boolean isDeleted() {
		return deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}



}
