package org.deals.framework.bean;

import java.util.HashSet;
import java.util.Set;

/**
 * AbstractCmsSection generated by MyEclipse Persistence Tools
 */

public abstract class AbstractCmsSection implements java.io.Serializable {

	// Fields

	private Integer cmssId;

	private String cmssName;

	private String cmssUri;

	private String cmssDescription;

	private String cmssShortdesc;
	
	private boolean cmssActive;
	
	private Integer cmssPosition;

	private Set AProfileSectionses = new HashSet(0);

	// Constructors

	/** default constructor */
	public AbstractCmsSection() {
	}

	/** minimal constructor */
	public AbstractCmsSection(Integer cmssId, String cmssName) {
		this.cmssId = cmssId;
		this.cmssName = cmssName;
	}

	/** full constructor */
	public AbstractCmsSection(Integer cmssId, String cmssName, String cmssUri,
			String cmssDescription, String cmssShortdesc, Set AProfileSectionses) {
		this.cmssId = cmssId;
		this.cmssName = cmssName;
		this.cmssUri = cmssUri;
		this.cmssDescription = cmssDescription;
		this.cmssShortdesc = cmssShortdesc;
		this.AProfileSectionses = AProfileSectionses;
	}

	// Property accessors

	public Integer getCmssId() {
		return this.cmssId;
	}

	public void setCmssId(Integer cmssId) {
		this.cmssId = cmssId;
	}

	public String getCmssName() {
		return this.cmssName;
	}

	public void setCmssName(String cmssName) {
		this.cmssName = cmssName;
	}

	public String getCmssUri() {
		return this.cmssUri;
	}

	public void setCmssUri(String cmssUri) {
		this.cmssUri = cmssUri;
	}

	public String getCmssDescription() {
		return this.cmssDescription;
	}

	public void setCmssDescription(String cmssDescription) {
		this.cmssDescription = cmssDescription;
	}

	public String getCmssShortdesc() {
		return this.cmssShortdesc;
	}

	public void setCmssShortdesc(String cmssShortdesc) {
		this.cmssShortdesc = cmssShortdesc;
	}

	public Set getAProfileSectionses() {
		return this.AProfileSectionses;
	}

	public void setAProfileSectionses(Set AProfileSectionses) {
		this.AProfileSectionses = AProfileSectionses;
	}

	public boolean isCmssActive() {
		return cmssActive;
	}

	public void setCmssActive(boolean cmssActive) {
		this.cmssActive = cmssActive;
	}

	public Integer getCmssPosition() {
		return cmssPosition;
	}

	public void setCmssPosition(Integer cmssPosition) {
		this.cmssPosition = cmssPosition;
	}

}