package org.deals.framework.bean;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AbstractUserProfile generated by MyEclipse Persistence Tools
 */

public abstract class AbstractUserProfile implements java.io.Serializable {

	// Fields

	private Integer upId;

	private String upName;

	private String upDescription;

	private Date upCreated;

	private Date upExpire;

	private Set userses = new HashSet(0);

	private Set AProfilePageses = new HashSet(0);

	private Set AProfileSectionses = new HashSet(0);

	// Constructors

	/** default constructor */
	public AbstractUserProfile() {
	}

	/** minimal constructor */
	public AbstractUserProfile(Integer upId, String upName, Date upCreated) {
		this.upId = upId;
		this.upName = upName;
		this.upCreated = upCreated;
	}

	/** full constructor */
	public AbstractUserProfile(Integer upId, String upName,
			String upDescription, Date upCreated, Date upExpire, Set userses,
			Set AProfilePageses, Set AProfileSectionses) {
		this.upId = upId;
		this.upName = upName;
		this.upDescription = upDescription;
		this.upCreated = upCreated;
		this.upExpire = upExpire;
		this.userses = userses;
		this.AProfilePageses = AProfilePageses;
		this.AProfileSectionses = AProfileSectionses;
	}

	// Property accessors

	public Integer getUpId() {
		return this.upId;
	}

	public void setUpId(Integer upId) {
		this.upId = upId;
	}

	public String getUpName() {
		return this.upName;
	}

	public void setUpName(String upName) {
		this.upName = upName;
	}

	public String getUpDescription() {
		return this.upDescription;
	}

	public void setUpDescription(String upDescription) {
		this.upDescription = upDescription;
	}

	public Date getUpCreated() {
		return this.upCreated;
	}

	public void setUpCreated(Date upCreated) {
		this.upCreated = upCreated;
	}

	public Date getUpExpire() {
		return this.upExpire;
	}

	public void setUpExpire(Date upExpire) {
		this.upExpire = upExpire;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

	public Set getAProfilePageses() {
		return this.AProfilePageses;
	}

	public void setAProfilePageses(Set AProfilePageses) {
		this.AProfilePageses = AProfilePageses;
	}

	public Set getAProfileSectionses() {
		return this.AProfileSectionses;
	}

	public void setAProfileSectionses(Set AProfileSectionses) {
		this.AProfileSectionses = AProfileSectionses;
	}

}