package org.deals.framework.bean;

// Generated Nov 9, 2008 4:23:54 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.xml.bind.annotation.XmlTransient;

/**
 * Comments generated by hbm2java
 */
public class AbstractComments implements PersistentObject, java.io.Serializable {

	private Long coId;
	
	@XmlTransient private WebPage webPage;
	private String commentAuthor;
	private String commentAuthorEmail;
	private String commentAuthorUrl;
	private String commentAuthorIp;
	private Date commentDate;
	private Date commentDateGmt;
	private String commentContent;
	private int commentApproved;
	private String commentAgent;
	private String commentType;
	private Integer usId;

	public AbstractComments() {
	}

	public AbstractComments(WebPage webPage, String commentAuthor,
			String commentAuthorEmail, int commentApproved) {
		this.webPage = webPage;
		this.commentAuthor = commentAuthor;
		this.commentAuthorEmail = commentAuthorEmail;
		this.commentApproved = commentApproved;
	}

	public AbstractComments(WebPage webPage, String commentAuthor,
			String commentAuthorEmail, String commentAuthorUrl,
			String commentAuthorIp, Date commentDate, Date commentDateGmt,
			String commentContent, int commentApproved, String commentAgent,
			String commentType, Integer usId) {
		this.webPage = webPage;
		this.commentAuthor = commentAuthor;
		this.commentAuthorEmail = commentAuthorEmail;
		this.commentAuthorUrl = commentAuthorUrl;
		this.commentAuthorIp = commentAuthorIp;
		this.commentDate = commentDate;
		this.commentDateGmt = commentDateGmt;
		this.commentContent = commentContent;
		this.commentApproved = commentApproved;
		this.commentAgent = commentAgent;
		this.commentType = commentType;
		this.usId = usId;
	}

	public Long getCoId() {
		return this.coId;
	}

	public void setCoId(Long coId) {
		this.coId = coId;
	}
	
	@XmlTransient public WebPage getWebPage() {
		return this.webPage;
	}

	public void setWebPage(WebPage webPage) {
		this.webPage = webPage;
	}

	public String getCommentAuthor() {
		return this.commentAuthor;
	}

	public void setCommentAuthor(String commentAuthor) {
		this.commentAuthor = commentAuthor;
	}

	public String getCommentAuthorEmail() {
		return this.commentAuthorEmail;
	}

	public void setCommentAuthorEmail(String commentAuthorEmail) {
		this.commentAuthorEmail = commentAuthorEmail;
	}

	public String getCommentAuthorUrl() {
		return this.commentAuthorUrl;
	}

	public void setCommentAuthorUrl(String commentAuthorUrl) {
		this.commentAuthorUrl = commentAuthorUrl;
	}

	public String getCommentAuthorIp() {
		return this.commentAuthorIp;
	}

	public void setCommentAuthorIp(String commentAuthorIp) {
		this.commentAuthorIp = commentAuthorIp;
	}

	public Date getCommentDate() {
		return this.commentDate;
	}

	public void setCommentDate(Date commentDate) {
		this.commentDate = commentDate;
	}

	public Date getCommentDateGmt() {
		return this.commentDateGmt;
	}

	public void setCommentDateGmt(Date commentDateGmt) {
		this.commentDateGmt = commentDateGmt;
	}

	public String getCommentContent() {
		return this.commentContent;
	}

	public void setCommentContent(String commentContent) {
		this.commentContent = commentContent;
	}

	public int getCommentApproved() {
		return this.commentApproved;
	}

	public void setCommentApproved(int commentApproved) {
		this.commentApproved = commentApproved;
	}

	public String getCommentAgent() {
		return this.commentAgent;
	}

	public void setCommentAgent(String commentAgent) {
		this.commentAgent = commentAgent;
	}

	public String getCommentType() {
		return this.commentType;
	}

	public void setCommentType(String commentType) {
		this.commentType = commentType;
	}

	public Integer getUsId() {
		return this.usId;
	}

	public void setUsId(Integer usId) {
		this.usId = usId;
	}

}
