package org.deals.framework.bean;





/**
 * AbstractAPageComponents generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractAProfilePages implements PersistentObject, java.io.Serializable {


    // Fields    

     private Integer aprId;
     private WebPage webPage;
     private UserProfile profile;
     private Integer aprLevel;


    // Constructors

    /** default constructor */
    public AbstractAProfilePages() {
    }

    
    /** semifull constructor */
    public AbstractAProfilePages(WebPage webPage, UserProfile userProfile) {
        this.webPage = webPage;
        this.profile = userProfile;
    }

    /** full constructor */
    public AbstractAProfilePages(WebPage webPage, UserProfile userProfile, Integer aprLevel) {
        this.webPage = webPage;
        this.profile = userProfile;
        this.aprLevel = aprLevel;
    }


    // Property accessors

	public Integer getAprId() {
		return aprId;
	}


	public void setAprId(Integer aprId) {
		this.aprId = aprId;
	}


	public Integer getAprLevel() {
		return aprLevel;
	}


	public void setAprLevel(Integer aprLevel) {
		this.aprLevel = aprLevel;
	}

	public UserProfile getProfile() {
		return profile;
	}


	public void setProfile(UserProfile profile) {
		this.profile = profile;
	}


	public WebPage getWebPage() {
		return webPage;
	}


	public void setWebPage(WebPage webPage) {
		this.webPage = webPage;
	}
    
    


	
	
}