package org.deals.framework.bean;

/**
 * AbstractAProfileSections generated by MyEclipse Persistence Tools
 */

public abstract class AbstractAProfileSections implements java.io.Serializable {

	// Fields

	private Integer apsId;

	private UserProfile userProfile;

	private CmsSection cmsSection;

	// Constructors

	/** default constructor */
	public AbstractAProfileSections() {
	}

	/** minimal constructor */
	public AbstractAProfileSections(Integer apsId) {
		this.apsId = apsId;
	}

	/** full constructor */
	public AbstractAProfileSections(Integer apsId, UserProfile userProfile,
			CmsSection cmsSection) {
		this.apsId = apsId;
		this.userProfile = userProfile;
		this.cmsSection = cmsSection;
	}

	// Property accessors

	public Integer getApsId() {
		return this.apsId;
	}

	public void setApsId(Integer apsId) {
		this.apsId = apsId;
	}

	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

	public CmsSection getCmsSection() {
		return this.cmsSection;
	}

	public void setCmsSection(CmsSection cmsSection) {
		this.cmsSection = cmsSection;
	}

}