package org.deals.framework.bean;




/**
 * AbstractAPagePage generated by MyEclipse - Hibernate Tools
 */
public abstract class AbstractAPagePage implements PersistentObject, java.io.Serializable {


    // Fields    
     private Integer appId;
     private WebPage webPageByAppChild;
     private WebPage webPageByAppParent;
     private Integer appWeight;


    // Constructors

    /** default constructor */
    public AbstractAPagePage() {
    }

	/** minimal constructor */
    public AbstractAPagePage(WebPage webPageByAppChild, WebPage webPageByAppParent) {
        this.webPageByAppChild = webPageByAppChild;
        this.webPageByAppParent = webPageByAppParent;
    }
    
    /** full constructor */
    public AbstractAPagePage(WebPage webPageByAppChild, WebPage webPageByAppParent, Integer appWeight) {
        this.webPageByAppChild = webPageByAppChild;
        this.webPageByAppParent = webPageByAppParent;
        this.appWeight = appWeight;
    }

   
    // Property accessors

    public Integer getAppId() {
        return this.appId;
    }
    
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    public WebPage getWebPageByAppChild() {
        return webPageByAppChild;
    }
    
    public void setWebPageByAppChild(WebPage webPageByAppChild) {
        this.webPageByAppChild = webPageByAppChild;
    }

    public WebPage getWebPageByAppParent() {
        return webPageByAppParent;
    }
    
    public void setWebPageByAppParent(WebPage webPageByAppParent) {
        this.webPageByAppParent = webPageByAppParent;
    }

    public Integer getAppWeight() {
        return this.appWeight;
    }
    
    public void setAppWeight(Integer appWeight) {
        this.appWeight = appWeight;
    }
   








}