package org.deals.framework.bean;

import java.util.Date;


/**
 * AbstractUtentiBollettaOnline generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractUtentiBollettaOnline implements PersistentObject, java.io.Serializable {


    // Fields    

     private String utente;
     private String pwd;
     private Date dataAttivaz;
     private String stato;
     private Date dataCessa;
     private Date dataUltimoAgg;
     private String mail;
     private Integer id;


    // Constructors

    /** default constructor */
    public AbstractUtentiBollettaOnline() {
    }

    
    /** full constructor */
    public AbstractUtentiBollettaOnline(String pwd, Date dataAttivaz, String stato, Date dataCessa, Date dataUltimoAgg, String mail, Integer id) {
        this.pwd = pwd;
        this.dataAttivaz = dataAttivaz;
        this.stato = stato;
        this.dataCessa = dataCessa;
        this.dataUltimoAgg = dataUltimoAgg;
        this.mail = mail;
        this.id = id;
    }

   
    // Property accessors

    public String getUtente() {
        return this.utente;
    }
    
    public void setUtente(String utente) {
        this.utente = utente;
    }

    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    public Date getDataAttivaz() {
        return this.dataAttivaz;
    }
    
    public void setDataAttivaz(Date dataAttivaz) {
        this.dataAttivaz = dataAttivaz;
    }

    public String getStato() {
        return this.stato;
    }
    
    public void setStato(String stato) {
        this.stato = stato;
    }

    public Date getDataCessa() {
        return this.dataCessa;
    }
    
    public void setDataCessa(Date dataCessa) {
        this.dataCessa = dataCessa;
    }

    public Date getDataUltimoAgg() {
        return this.dataUltimoAgg;
    }
    
    public void setDataUltimoAgg(Date dataUltimoAgg) {
        this.dataUltimoAgg = dataUltimoAgg;
    }

    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
   








}