package org.deals.framework.bean;

import java.util.Date;

/**
 * APageComponents generated by MyEclipse - Hibernate Tools
 */
public class APageComponents extends AbstractAPageComponents implements java.io.Serializable {

	// Serve per l'editing sul Repeater
	private int rowId;

	// Constructors

	/** default constructor */
	public APageComponents() {
	}

	public APageComponents(int apcId, WebPage webPage, APageComponentsType APageComponentsType, WebComponent webComponent, Date apcAssocDate, String apcAlt, String apcDescription) {
		super(apcId, webPage, APageComponentsType, webComponent, apcAssocDate, apcAlt, apcDescription);
	}

	public APageComponents(int apcId, WebPage webPage, WebComponent webComponent) {
		super(apcId, webPage, webComponent);
	}

	public int getRowId() {
		return rowId;
	}

	public void setRowId(int rowId) {
		this.rowId = rowId;
	}

	public String toXML() {
		StringBuffer sb = new StringBuffer();
		sb.append("<web-resource id=\"" + getWebComponent().getWcId() + "\" type=\"" + getAPageComponentsType().getApctName() + "\">");
		sb.append(getWebComponent().toXML2());
		sb.append("<description>" + (getApcDescription()==null?"":getApcDescription())+ "</description>");
		sb.append("</web-resource>");
		return sb.toString();
	}

}
