package org.deals.framework.bean;

// Generated by MyEclipse Persistence Tools

/**
 * AProfileSections generated by MyEclipse Persistence Tools
 */
public class AProfileSections extends AbstractAProfileSections implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public AProfileSections() {
	}

	/** minimal constructor */
	public AProfileSections(Integer apsId) {
		super(apsId);
	}

	/** full constructor */
	public AProfileSections(Integer apsId, UserProfile userProfile,
			CmsSection cmsSection) {
		super(apsId, userProfile, cmsSection);
	}

}
