package org.deals.framework.bean;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;

import org.deals.framework.factory.PageStateFactory;


/**
 * PageState generated by MyEclipse - Hibernate Tools
 */
public class PageState extends AbstractPageState implements java.io.Serializable {

	private static final long serialVersionUID = -6756957572308785564L;

	public final static int DRAFT_ID = 1;
	public final static int PUBLISHED_ID = 2;
	public final static int EXPIRED_ID = 3;
	public final static int DELETED_ID = 4;

	public final static String DRAFT_NAME = "bozza";
	public final static String PUBLISHED_NAME = "pubblicato";
	public final static String EXPIRED_NAME = "scaduto";
	public final static String DELETED_NAME = "eliminato";
	
    // Constructors

    /** default constructor */
    public PageState() {
    }

	/** minimal constructor */
    public PageState(String psName) {
        super(psName);        
    }
    
    /** full constructor */
    public PageState(String psName, String psDescription, Set webPages) {
        super(psName, psDescription, webPages);        
    }
   
    
    public static PageState DRAFT() {
    	return PageStateFactory.createDraftPageState();
    }

    public static PageState PUBLISHED() {
    	return PageStateFactory.createPublishedPageState();
    }

    public static PageState EXPIRED() {
    	return PageStateFactory.createExpiredPageState();
    }

    public static PageState DELETED() {
    	return PageStateFactory.createDeletedPageState();
    }
    
    // TODO sistemare, dovrebbe dare eccezione se non trova lo stato o roba simile
    public static PageState getStateByName(String name) {
    	if (name.equals(DRAFT_NAME)) return DRAFT();
    	if (name.equals(PUBLISHED_NAME)) return PUBLISHED();
    	if (name.equals(EXPIRED_NAME)) return EXPIRED();
    	if (name.equals(DELETED_NAME)) return DELETED();
    	return null;
    }
    
    
	@Override
	public boolean equals(Object obj) {
		if (obj == null) return false;
		if (obj == this) return true;
		if (!(obj instanceof PageState)) return false;		
		return ((PageState)obj).getPsId().equals(getPsId());
	}

	public String toXML() {
		return this.getPsName();
	}    
    
}
